version: '3.8'

services:
  mongo_db:
      image: mongo:4.4.10
      container_name: db_container
      restart: always
      ports:
        - 27017:27017
      volumes:
        - mongo_db:/data/db
      command: mongod  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3005:3005
    environment:
      PORT: 3005
      NODE_ENV: production
      DATABASE: mongodb://mongo_db:27017
      DATABASE_PASSWORD: root
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
  

