version: '3.8'

services:
  mongo_db:
    image: mongo:4.4.10
    container_name: db_container
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
    command: mongod
  api:
    image: backend:10
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3005:3005
    environment:
      PORT: 3005
      NODE_ENV: production
      DATABASE: mongodb://mongo_db:27017
      DATABASE_PASSWORD: root
    depends_on:
      - mongo_db
  web:
    image: frontend:10
    build: ./frontend
    depends_on:
      - api
    environment:
      PORT: 5173
    ports:
      - 5173:5173
    command: npm run dev -- --host

volumes:
  mongo_db: {}
